articles/urls.py
from django.urls import path

from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.ArticleIndex.as_view(), name='index'),
    # old index view, as method
    # path('', views.index, name='index'),
    path('<int:pk>/', views.ArticleDetail.as_view(), name='detail'),
    # keywords path, keyword name is described as unique in the model
    path('keywords/<str:the_keyword_name>/', views.KeywordIndex.as_view(), name='keyword'),
]


# try to make article detail urls from article slugs
# https://docs.djangoproject.com/en/2.0/ref/contrib/admin/#django.contrib.admin.ModelAdmin.prepopulated_fields
# https://docs.djangoproject.com/en/2.0/topics/http/urls/
# https://docs.djangoproject.com/en/2.0/ref/models/fields/#slugfield

dj7s/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('index/', views.index, name='index'),
    path('who_we_are/', views.who_we_are, name='who_we_are'),
    path('matrix/', views.matrix, name='matrix'),
    path('innovation_culture/', views.innovation_culture, name='innovation_culture'),

    path('news/', include('articles.urls')),

    path('polls/', include('polls.urls')),

    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
import datetime
import re

from django.db import models
from django.utils import timezone

from ckeditor.fields import RichTextField


# Create your models here.


def slug_default(article_title):
    # if character not in [0-9a-zA-Z], or one of $-_.+!*'(), it is converted to underscore
    slug_name=""
    for char in article_title[:50]:
        if not re.match("[a-zA-z0-9$-_+()]", char):
            char='_'
        slug_name += char
    return slug_name



class Article(models.Model):
    article_title = models.CharField(max_length=200, default="")
    pub_date = models.DateTimeField('date published', default=timezone.now)
    article_slug = models.SlugField(max_length=50, default=slug_default(str(article_title)))
    article_body = RichTextField(default="")

    def __str__(self):
        return self.article_title

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'



class Image(models.Model):
    image_name = models.CharField(max_length=200)
    article_image = models.ImageField(upload_to='dj7s/article_images/%Y/%m/%d', blank=True)
    image_alt = models.CharField(max_length=200, blank=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    def __str__(self):
        return self.image_name



class Keyword(models.Model):
    keyword_name = models.CharField(max_length=200, unique=True)
    keyword_desc = models.CharField(max_length=500)
    # article = models.ForeignKey(Article, on_delete=models.CASCADE)
    taxonomies = models.ManyToManyField(Article, through="Taxonomy")
    def __str__(self):
        return self.keyword_name



class Taxonomy(models.Model):
    """ Represents intermediate table of many to many Article-Keyword relationship."""
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    keyword = models.ForeignKey(Keyword, on_delete=models.CASCADE)

# add taxonomy and maybe make fields names unique

articles/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import generic


from .models import Article, Image, Keyword, Taxonomy
# Create your views here.

# def index(request):
#     latest_article_list = Article.objects.order_by('-pub_date')[:5]
#     context = {'latest_article_list': latest_article_list, "nbar":"news"}
#     return render(request, 'articles/index.html', context)

class ArticleIndex(generic.ListView):
    template_name = 'articles/index.html'
    context_object_name = 'latest_article_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Article.objects.order_by('-pub_date')[:5]

    def get_context_data(self, **kwargs):
        """ This extends the generic view, adding the related images to the
        returned context:
        https://docs.djangoproject.com/en/2.0/topics/class-based-views/generic-display/#adding-extra-context
        """
        context = super().get_context_data(**kwargs)
        context['nbar'] = 'news'
        return context



# def detail(request):
#     return render(request, 'articles/detail.html', context)

class ArticleDetail(generic.DetailView):
    model = Article
    template_name = 'articles/detail.html'

    def get_context_data(self, **kwargs):
        """ This extends method override(?) the generic view, adding the related images to the
        returned context.
        """
        context = super().get_context_data(**kwargs)
        context['images_list'] = Image.objects.filter(article__id=self.get_object().pk)
        context['keywords_list'] = Keyword.objects.filter(taxonomy__article=self.get_object().pk)
        return context



class KeywordIndex(generic.ListView):
    template_name = 'articles/keyword.html'
    context_object_name = 'keyword_article_list'

    def get_queryset(self):
        """Return articles with with that contain the same keyword."""
        # keyword_pr_key = Keyword.objects.get(keyword_name=self.kwargs['the_keyword_name'])
        # pr_key = Keyword.objects.filter(keyword_name='forest')
        # object_list = Taxonomy.objects.filter(keyword_name = self.kwargs['the_keyword_name'])
        return Article.objects.filter(keyword__keyword_name=self.kwargs['the_keyword_name'])

articles/templates/articles/detail.html
{% extends 'dj7s/base.html' %}
{% load static %}


{% block title %} seven sigma | Home {% endblock title %}



{% block script %}
	<script type="text/javascript" src="{% static 'dj7s/js/jquery.min.js' %}"></script>
{% endblock script %}



{% block page_banner %}
    <!-- page-banner-section
			================================================== -->
    <section class="page-banner-section">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <h2>News</h2>
          </div>
        </div>
      </div>
    </section>
    <!-- End page-banner section -->
{% endblock page_banner %}




{% block content_section %}

<section class="projects-page-section">
  <div class="container">
    <div class="project-title title">
      <h2 class="box-header">{{article.article_title}}</h2>
    </div>

    {{article.article_body | safe}}

		<hr>

		<p>

			<!-- AddToAny BEGIN -->
			<div class="a2a_kit a2a_kit_size_32 a2a_default_style pull-right">
			<a class="a2a_button_facebook"></a>
			<a class="a2a_button_linkedin"></a>
			<a class="a2a_button_twitter"></a>
			<a class="a2a_button_pocket"></a>
			<a class="a2a_button_email"></a>
			<a class="a2a_button_print"></a>
			</div>
			<script>
			var a2a_config = a2a_config || {};
			a2a_config.num_services = 6;
			a2a_config.color_main = "D7E5ED";
			a2a_config.color_border = "1385ca";
			a2a_config.color_link_text = "333333";
			a2a_config.color_link_text_hover = "333333";
			</script>
			<script async src="https://static.addtoany.com/menu/page.js"></script>
			<!-- AddToAny END -->

		{% block keywords %}
		<b>Related keywords:</b>
			{% for keyword in keywords_list %}
				<a href="/news/keywords/{{keyword.keyword_name}}/">{{keyword.keyword_name}}</a>,
			{% endfor %}
		{% endblock keywords %}

	</p>
  </div>
</br></br></br>

{% include 'dj7s/gallery.html' %}

</section>

{% endblock content_section %}

articles/templates/articles/index.html
{% extends 'dj7s/base.html' %}
{% load static %}

{% block title %}seven sigma | News{% endblock title %}

{% block script %}
<script type="text/javascript" src="{% static 'dj7s/js/jquery.min.js' %}"></script>
{% endblock script %}


{% block page_banner %}
    <!-- page-banner-section
			================================================== -->
    <section class="page-banner-section">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <h2>News</h2>
          </div>
        </div>
      </div>
    </section>
    <!-- End page-banner section -->
{% endblock page_banner %}


{% block content_section %}
<section class="services-page-section">
<div class="container">
  <div class="row">
  <div class="fb-page col-md-4"  data-href="https://www.facebook.com/ddikastes/" data-tabs="timeline" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><blockquote cite="https://www.facebook.com/ddikastes/" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/ddikastes/">Διοικητικοί Δικαστές</a></blockquote></div>
<div class="col-md-8">
<div class="services-wrapp">
{% if latest_article_list %}

    <ul style="list-style-type:none;">
      {% for article in latest_article_list %}

        <div class="services-post">
        <li>
          <div class="project-title title">
            <h2 class="box-header"><a href="{% url 'articles:detail' article.id %}">{{article.article_title}}</a></h2>
          </div>
          <p>{{ article.article_body |safe}}</p></li>
        </div>

      {% endfor %}
      </div>
    </ul>
  {% else %}
    <p>No articles are available.</p>
  {% endif %}
  </div>
  </div>
</div>
</section>
{% endblock content_section %}

articles/templates/articles/keyword.html
{% extends 'dj7s/base.html' %}
{% load static %}



{% block title %} seven sigma | Home {% endblock title %}



{% block script %}
	<script type="text/javascript" src="{% static 'dj7s/js/jquery.min.js' %}"></script>
{% endblock script %}



{% block page_banner %}
    <!-- page-banner-section
			================================================== -->
    <section class="page-banner-section">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <h2>News</h2>
          </div>
        </div>
      </div>
    </section>
    <!-- End page-banner section -->
{% endblock page_banner %}



{% block content_section %}
<section class="services-page-section">
<div class="container">
  <div class="row">
  <div class="fb-page col-md-3"  data-href="https://www.facebook.com/ddikastes/" data-tabs="timeline" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><blockquote cite="https://www.facebook.com/ddikastes/" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/ddikastes/">Διοικητικοί Δικαστές</a></blockquote></div>
<div class="col-md-9">
<div class="services-wrapp">
{% if keyword_article_list %}

    <ul style="list-style-type:none;">
      {% for article in keyword_article_list %}

        <div class="services-post">
        <li>
          <div class="project-title title">
            <h2 class="box-header"><a href="{% url 'articles:detail' article.id %}">{{article.article_title}}</a></h2>
          </div>
          <p>{{ article.article_body |safe}}</p></li>
        </div>

      {% endfor %}
      </div>
    </ul>
  {% else %}
    <p>No articles are available.</p>
  {% endif %}
  </div>
  </div>
</div>
</section>
{% endblock content_section %}